### ISSUE TITLE
Training Failed

### ISSUE THREAD

**Issue by sachinshelke** [cloud-annotations/custom-training#1]
Hi,

I'm trying to train model as per guideline of cloud annotation cli.
Following steps has been done
1. Created object storage and bucket
2. Created ML instance
3. using cloud.annotation.ai
3.a. --> Uploaded Images
3.b. --> Labeled Images
4. Using Cloud Annotation Cli
4.a --> Initialised cli with credentials and training configuration (gpu=v100x2 & steps=500/1000/5000/10000)
4.b --> Started training using cacli train trainer.zip

Once all above steps done --> Progress shows with messages
`Preparing to train (this may take a while)...`
message shows around 30 min and then done.

But whenever i started the training it is failing. 
I have my company account as well as personal account too. 
On the both account training get failed with following error. (Error extracted from IBM Cloud storage bucket)

Gone through training-status.json on cloud bucket and following error return

```
"status": {
      "state": "error",
      "finished_at": "2019-07-23T06:31:31.903Z",
      "submitted_at": "2019-07-23T06:26:57.293Z",
      "error": {
        "trace": "",
        "errors": [{
          "code": "dl_job_failed (S100)",
          "message": "Internal error (S100)",
          "more_info": "http://watson-ml-api.mybluemix.net/"
        }]
      },
      "message": "training-a072AJHZg: INSUFFICIENT_RESOURCES",
      "metrics": [],
      "current_at": "2019-07-23T06:31:32.784Z",
      "error_cause": "system"
    }
```

Error Received through ibm cli

```
Training with training/test data at:
DATA_DIR: /mnt/data/prod.bucket
MODEL_DIR: /job/model-code
TRAINING_JOB: 
TRAINING_COMMAND: cd "$(dirname "$(find . -name "start.sh" -maxdepth 2 | head -1)")" && ./start.sh 1000
Storing trained model at:
RESULT_DIR: /mnt/results/prod.bucket.train/training-Sw9aGBNZR
Wed Jul 24 06:58:31 UTC 2019: Running Tensorflow job
/usr/local/bin/train.sh: line 38: ./start.sh: Permission denied
Training exited with error code 126
Failed: learner_exit_code: 126
```

I did tried searching error in IBM docs but there is no luck and not getting any details about it.

Please respond as we are using IBM platform for production object detection purpose.

Thanks

**Comment by bourdakos1** [comment]
Watson machine learning changed the way they handle file permissions over the weekend. You’ll need to update cacli to the latest version (1.1.4) as for the “INSUFFICIENT RESOURCES” error are you using a lite tier? Or did you upgrade to standard?

**Comment by sachinshelke** [comment]
Thanks.
I'm using standard plan.
Have updated cli. Started training again. Will see what will be the result now.

**Comment by bourdakos1** [comment]
Were you able to get it running?

**Comment by sachinshelke** [comment]
Hi,
Thanks, yes. it is woking fine. 
Please close the issue.
I have another issue. Will separate create ticket for the same.

**Comment by divijbajaj5** [comment]
My model is trained completely. I'm getting a success message as follows:
success Training in progress.
success Model files saved to bucket.
✨ Done.

C:\Users\Divij Bajaj>cacli download model-2imjsmrm
Training was canceled or failed.

C:\Users\Divij Bajaj>cacli download model-2imjsmrm
Training was canceled or failed.

Model is not getting downloaded

**Comment by bourdakos1** [comment]
you are using an old version of cacli, you need to uninstall it and install the new version

**Comment by divijbajaj5** [comment]
Please send link from where to install and the procedure how to do it. TIA

**Comment by bourdakos1** [comment]
the instructions are on: https://github.com/cloud-annotations/training

**Comment by divijbajaj5** [comment]
I'm downloading the file and installing but it is not getting installed. 
cacli_windows_x86_64.exe
Please help :?

**Comment by bourdakos1** [comment]
I’m not too familiar with windows, I’ve asked my friend for help. I’ll keep you updated with instructions

**Comment by bourdakos1** [comment]
Okay, so you'll want to rename `cacli_windows_x86_64.exe` to `cacli.exe`
Then to use the tool, open cmd prompt and cd into the folder that you downloaded it to and run `cacli`

If you want to access `cacli` from anywhere, you need to put it in a folder on your `PATH`

**Comment by divijbajaj5** [comment]
Thanks for this help, it worked. So I have successfully trained and downloaded model. Now how to start local host as NPM is uninstalled. Do I have to install NVM ?

**Comment by bourdakos1** [comment]
You should still have NPM installed, NPM is just a package manager for node. You previously used NPM to install cacli, that version of cacli no longer works, but NPM should still be there

**Comment by divijbajaj5** [comment]
Okay so I have started the server using command NPM start. It is showing this 
You can now view tensorflowjs-object-detection in the browser.

  http://localhost:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.
I can see my webcam light on at this local host but nothing is dislaying. I ran 3-4 times but no luck, I can't see my face !!

**Comment by bourdakos1** [comment]
What browser are you using? Try chrome

**Comment by divijbajaj5** [comment]
Using chrome only

**Comment by bourdakos1** [comment]
are there any errors in the web inspector?
