### ISSUE TITLE
Convert & Download Web Model is missing

### ISSUE THREAD

**Issue by sachinshelke** [cloud-annotations/custom-training#2]
Hi,
While doing custom training. 
Training done properly however, Convert to web / tflite part is missing in script.
Is there any way to convert model after training. I have trained model and waited for almost 12 hrs for 200K Steps using faster r-cnn.

Please help. Otherwise i have to start training again.
Thanks

**Comment by bourdakos1** [comment]
It might be difficult converting faster rcnn to TensorFlow.js. There’s a lot of operations that aren’t supported by TensorFlow.js so you’d have to strip them out and manually build them in JavaScript. You can check out the conversion code for the MobileNet model, it might be similar to that, but things will probably be named different. Another thing to consider is that faster rcnn will be very slow running in the browser and might even perform faster running models on the server

**Comment by sachinshelke** [comment]
Wow. This help a lot. Thank. 
Will start normal training again as it is weekend. Hopefully will finished by tomorrow.
No Rush.
Cheers.
